version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  matrix-app:
    image: matrix-compute-redis
    container_name: matrix-redis
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
    depends_on:
      - redis
