server.port=8080
spring.application.name=matrix-compute-redis
management.endpoints.web.exposure.include=health

# Redis Cache
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
